//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatisticData
    {
        public int Id { get; set; }
        public short Gender { get; set; }
        public int WeightFrom { get; set; }
        public int WeigthTo { get; set; }
        public int DayKcal { get; set; }
        public int DayFats { get; set; }
        public int DayProtein { get; set; }
        public int DayCarnohydrates { get; set; }
    }
}
